### ISSUE TITLE
Improve retrospectives

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#44]
There are some basic changes to make that can fix some low-hanging-fruit problems. After that, we need to pick one of two options: stick with the CLI and make it as good as possible, or build a GUI for the flex panel.

#### Collapse teammate feedback questions into one

Instead of two separate questions/answers for teammate feedback, just use one:

```
Give feedback to your teammate by completing the following sentence:

"{{subject}}, I want to work with you because... and I would want to work with you more if..."
```

## Improvement Option 1: Retro Form in Flex Panel

Switch to a GUI. Use similar flow to `/vote`.

- [ ] Disable `/log` command
- [ ] Make `/retro` command that opens retrospective panel
- [ ] Create paginated retrospective form template

Sketch mockup for form pages:

![retro 1](https://cloud.githubusercontent.com/assets/709100/16630461/5d46be12-436f-11e6-81fb-8abcfdfa7885.png)
![retro 2](https://cloud.githubusercontent.com/assets/709100/16630462/5e894952-436f-11e6-8396-67286d2114c9.png)

## Improvement Option 2: Improved CLI

Use the same command structure but modify behavior to make UX less painful.

- [ ] With `/log -r`, don't show all questions. Only show progress and the next unanswered question.
- [ ] Provide a copy-pasteable example command with each question, so that learners run into fewer syntax errors.
- [ ] After answering a question, show the next unanswered question. This way learners don't need to issue a separate command to see the next question after answering one.
- [ ] Add guideline: avoid Echo responses that take up more than 1/3 of vertical screen. Having gigantic responses sucks, because it removes the visibility of history and thus context.

**Comment by tannerwelsh** [comment]
Thanks for the ideas @shereefb

**Comment by tannerwelsh** [comment]
Updated the description with some initial ideas and thoughts in prep for talk w/ @prattsj later.

**Comment by bundacia** [comment]
@tannerwelsh / @prattsj -  One thing to keep in mind is that whatever we come up with will need to support players that are in multiple projects (and therefore have multiple retro's to fill out). So `/retro` might need to take an optional project param so that mentors can do `/retro #furry-kitten` or whatever.

**Comment by prattsj** [comment]
@bundacia: resolved. discussed w/ @tannerwelsh. project name param optional if the player is only on one project team, required if on multiple teams. should give an error message to that effect as needed.

**Comment by bundacia** [comment]
Cool. FYI: I've added support for for a `projectName` param to the "get the survey" API (https://github.com/LearnersGuild/game/pull/237). The work I did there should be useful when we create this UI as well.

**Comment by jeffreywescott** [comment]
Related: https://github.com/LearnersGuild/learning-os-software/issues/126

**Comment by tannerwelsh** [comment]
Aright broke this up into epic w/ sub-issues and moved all to Backlog.

**Comment by tannerwelsh** [comment]
As a plan B, here's a SurveyMonkey form: https://www.surveymonkey.com/r/los-retro. Hope it doesn't come to that, but it would be totally fine if we had to use it.
